name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    uses: EventHubConnect/github-workflows/.github/workflows/semantic_release.yml@main
    secrets:
      token: ${{ secrets.GH_TOKEN }}
