name: Release

on:
  push:
    branches:
      - 'main'

jobs:
  release:
    uses: EventHubConnect/github-workflows/.github/workflows/semantic_release.yml@master
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
